/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: "doc",
      id: "intro",
      label: "Welcome to SkyPoint Documentation"
    },
    {
      type: "doc",
      id: "overview",
      label: "Overview"
    },
    {
      type: "category",
      label: "Release Notes",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "skypointreleases",
          label: "SkyPoint Releases"
        },
        {
          type: "doc",
          id: "AllReleases",
          label: "All Releases"
        },
        {
          type: "category",
          label: "Relase Versions",
          items: [
            {
              type: "doc",
              id: "v7.0.0",
              label: "7.0.0"
            },
            {
              type: "doc",
              id: "v6.3.0",
              label: "6.3.0"
            },
            {
              type: "doc",
              id: "v6.2.1",
              label: "6.2.1"
            },
            {
              type: "doc",
              id: "v6.2.0",
              label: "6.2.0"
            },
            {
              type: "doc",
              id: "v6.1.0",
              label: "6.1.0"
            },
            {
              type: "doc",
              id: "v6.0.0",
              label: "6.0.0"
            },
            {
              type: "doc",
              id: "v5.1.0",
              label: "5.1.0"
            },
            {
              type: "doc",
              id: "v5.0.0",
              label: "5.0.0"
            },
            {
              type: "doc",
              id: "v4.4.0",
              label: "4.4.0"
            }, {
              type: "doc",
              id: "v4.3.0",
              label: "4.3.0"
            }, {
              type: "doc",
              id: "v4.2.0",
              label: "4.2.0"
            },{
              type: "doc",
              id: "v4.1.0",
              label: "4.1.0"
            },,{
              type: "doc",
              id: "v4.0.0",
              label: "4.0.0"
            },{
              type: "doc",
              id: "v3.0.0",
              label: "3.0.0"
            },{
              type: "doc",
              id: "v2.2.0",
              label: "2.2.0"
            },{
              type: "doc",
              id: "v2.1.0",
              label: "2.1.0"
            },{
              type: "doc",
              id: "v2.0.0",
              label: "2.0.0"
            },{
              type: "doc",
              id: "v1.0.0",
              label: "1.0.0"
            },{
              type: "doc",
              id: "whats-new-skypoint",
              label: "Previous releases"
            }
          ]
        }
      ]

    },
    {
      type: "category",
      label: "Get started",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "signup",
          label: "Sign up"
        },
        {
          type: "doc",
          id: "login",
          label: "Log in"
        }
      ]
    },

    {
      type: "doc",
      id: "home",
      label: "Dashboard"
    }, {
      type: "doc",
      id: "SkyPointGPT",
      label: "SkyPointGPT"
    },
    {
      type: "category",
      label: "Dataflow",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "dataflows",
          label: "Overview"
        },
        {
          type: "doc",
          id: "imports",
          label: "Imports"
        },
        {
          type: "doc",
          id: "exports",
          label: "Exports"
        },
        {
          type: "category",
          label: "Transformations",
          collapsed: true,
          collapsible: true,
          items: [
            {
              type: "doc",
              id: "transformations",
              label: "Overview"
            },
            {
              type: "doc",
              id: "Transformations-dbtCore",
              label: "Transformation with dbt Core"
            }, {
              type: "doc",
              id: "datalineage",
              label: "Data lineage"
            }
          ]
        },
        {
          type: "doc",
          id: "types",
          label: "Types"
        },
        {
          type: "category",
          label: "Connectors",
          collapsed: true,
          collapsible: true,
          items: [
            {
              type: "doc",
              id: "connectors",
              label: "Overview"
            },
            {
              type: "category",
              collapsed: true,
              collapsible: true,
              label: "Import connectors",
              items: [
                {
                  type: "doc",
                  id: "importconnectors",
                  label: "Overview"
                },
                {
                  type: "doc",
                  id: "awscognito",
                  label: "AWS Cognito"
                }, {
                  type: "doc",
                  id: "amazonredshift",
                  label: "Amazon Redshift"
                },{
                  type: "doc",
                  id: "amazonsthree",
                  label: "Amazon S3"
                },{
                  type: "doc",
                  id: "azureblobstorage",
                  label: "Azure Blob Storage"
                },{
                  type: "doc",
                  id: "azuredatalakestoragegen2",
                  label: "Azure Data Lake Storage"
                },

              ]
            },

          ]
        }
      ]
    },

      "home",
      "export",
      "entities",
      "actions",
      "api",
      "automate"


    // 'welcomedocs',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],

};

module.exports = sidebars;
