/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: "doc",
      id: "intro",
      label: "Welcome to SkyPoint Documentation"
    },
    {
      type: "doc",
      id: "overview",
      label: "Overview"
    },
    {
      type: "category",
      label: "Release Notes",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "skypointreleases",
          label: "SkyPoint Releases"
        },
        {
          type: "doc",
          id: "AllReleases",
          label: "All Releases"
        },
        {
          type: "category",
          label: "Relase Versions",
          items: [
            {
              type: "doc",
              id: "v4.4.0",
              label: "4.4.0"
            }, {
              type: "doc",
              id: "v4.3.0",
              label: "4.3.0"
            }, {
              type: "doc",
              id: "v4.2.0",
              label: "4.2.0"
            },{
              type: "doc",
              id: "v4.1.0",
              label: "4.1.0"
            },,{
              type: "doc",
              id: "v4.0.0",
              label: "4.0.0"
            },{
              type: "doc",
              id: "v3.0.0",
              label: "3.0.0"
            },{
              type: "doc",
              id: "v2.2.0",
              label: "2.2.0"
            },{
              type: "doc",
              id: "v2.1.0",
              label: "2.1.0"
            },{
              type: "doc",
              id: "v2.0.0",
              label: "2.0.0"
            },{
              type: "doc",
              id: "v1.0.0",
              label: "1.0.0"
            },{
              type: "doc",
              id: "whats-new-skypoint",
              label: "Previous releases"
            }
          ]
        }
      ]

    },
      "home",
      "export",
      "entities",
      "actions",
      "api",
      "automate"


    // 'welcomedocs',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],

};

module.exports = sidebars;
